### ISSUE TITLE
install section vs release section

### ISSUE THREAD

**Issue by keiranmraine** [cancerit/archCompare#11]
The "Cutting a release" section has been updated to generate a wheel archive but:

1. The scp command shows an egg archive rather than something like:
  * `archCompare-X.X.X-py3-none-any.whl`
2. "Install" section still describes using `easy_install` and an egg, should be able to use pip as:
  * `pip install --find-links=~/my-wheels archCompare`

**Comment by sb43** [comment]
Corrected in release 1.1.0

**Comment by keiranmraine** [comment]
@sb43 , can you put proper release notes on the release please

**Comment by sb43** [comment]
done
