### ISSUE TITLE
zdiff differs on OSX

### ISSUE THREAD

**Issue by drjsanger** [cancerit/archCompare#18]
Currently the tests will fail on OSX as `zdiff` [(see here for example)](https://github.com/lionheart/openradar-mirror/issues/1640) is different. Perhaps we should detect OS and change tool appropriately?

**Comment by sb43** [comment]
Need to be investigated

**Comment by keiranmraine** [comment]
This won't be something that will be the responsibility of the code base under the new model.  If someone want's to be portable they will have to use the preprocessor to zcat/gunzip the files in advance.

**Comment by sb43** [comment]
Closing as out of scope of this project
