### ISSUE TITLE
no required arguments

### ISSUE THREAD

**Issue by byb121** [cancerit/archCompare#5]
From what I understand I think options `-a`, `-b`, `-j` are required arguments, command line without specifying them should exit immediately. However, see below:
```
$ cgpCompare -q
Running analysis, please check log file for any errors 
detailed results in results.tsv file
Can not find json file (2, 'No such file or directory')
```
The log file should not be created before the program actually runs, I think.

**Comment by sb43** [comment]
Corrected in release 1.1.0
