### ISSUE TITLE
identical archive is allowed

### ISSUE THREAD

**Issue by byb121** [cancerit/archCompare#8]
It runs if I give `-a` and `-b` the same file path, better to give an error and exit?

**Comment by sb43** [comment]
This is upto user what he wants to compare, closing issue

**Comment by keiranmraine** [comment]
@sb43, that should still raise at least a warning or 'Are you sure?' prompt.  Also ensure that it compares actual paths incase the same data is accessed via a symlink

**Comment by sb43** [comment]
Corrected in release 1.1.0
